### ISSUE TITLE
Gestioni pulsanti fisici

### ISSUE THREAD

**Issue by pmarchini** [LucaCarrero/espBoy_Lib#1]
Ho guardato entrambe le possibilità e mi piacciono entrambe, per tanto direi :
E lasciarle disponibili entrambe ? 
Permettere da libreria di indicare un puntatore a funzione oppure di accedere direttamente allo stato del pulsante ? 
Magari permettere anche di abilitare o disabilitare la chiamata automatica di funzione in modo da rendere più versatile ?

**Comment by LucaCarrero** [comment]
la parte statica è fatta b8a46a8 e 29556bfe316bb0ac4733a8b0e4228f9b53689329.
Supporta entrambe le modalità come da te consigliatomi.

TODO:
1) salvataggio di una mappatura dei tasti
2) caricamento di una mappatura dei 
3) compatibilità con pulsanti normali

**Comment by pmarchini** [comment]
Ti consiglierei di creare per i 3 elementi della todo list delle issue separate e magari di creare un progetto annesso in modo da poter avere una bacheca degli sviluppi che stai compiendo.
Questo in primis per tenere traccia dell'evoluzione del progetto e in secondo luogo per permettere ad altri, in futuro o anche ora, di collaborare!

**Comment by LucaCarrero** [comment]
fbd694f1d3b2323f49bfa4cf550e04234208e821

Finito la gestione dei pulsanti fisici, dimmi cosa ne pensi se secondo te c'è qualcosa da cambiare la modifico altrimenti chiudi pure questa issue che apriamo quella per i gameObject. 
Per le issue della todo list ormai ci stavo già sviluppando su e avevo già quasi finito era solo per tenere traccia dei commit. la prossima terrò in considerazione il consiglio.
